---
# tasks file for Filebeat
#
# #
# Installing Filebeat
#

# Install Filebeat

- name: Install Filebeat with apt
  apt:
   name: filebeat
   update_cache: yes

- name: Create filebeat config
  template:
    src:  files/filebeat.yml  
    dest: /etc/filebeat/filebeat.yml


# Starting Filebeat

- name: Starting/Restarting Filebeat
  service:
   name: filebeat
   state: restarted
