---
# tasks file for Filebeat
#
# #
# Installing Filebeat
#

# Install Filebeat

- name: Install Filebeat with apt
  apt:
   name: filebeat
   update_cache: yes

- name: Updating filebeat config
  template:
    src:  filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml


# Starting Filebeat

- name: Starting/Restarting Filebeat
  service:
   name: filebeat
   state: restarted
