---
#
# Installing Filebeat
#

# Install Filebeat 

- name: Install Filebeat with apt
  apt:
   name: filebeat
   update_cache: yes

- name: Create filebeat config
  template:
    src: filebeat.config.j2
    dest: /etc/filebeat/filebeat.yml


# Starting Filebeat

- name: Starting/Restarting Filebeat
  service:
   name: filebeat
   state: restarted
