---
# tasks file for Logstash
#
- name: Add Logstash GPG key.
  apt_key:
    url: "{{ apt_key_url }}"
    state: present

- name: Add Logstash apt repository.
  apt_repository:
    repo: "{{ apt_repo_url }}"
    state: present



- name: Install Logstash.
  apt:
    name: logstash
    state: present


- name: Updating Logstash configuration
  template:
     src: "{{ item.src }}"
     dest: "{{ item.dest }}"
  with_items:
      - { src: 'templates/logstash.conf.j2', dest: '/etc/logstash/logstash.conf' }
      - { src: 'templates/logstash.yml.j2', dest: '/etc/logstash/logstash.yml' }
     

- name: Starting Logstash
  service:
    name: logstash
    state: restarted

