---
# tasks file for Kibana
#
# # Installing Kibana
#

# Install Kibana

- name: Install Kibana with apt
  apt:
   name: kibana
   update_cache: yes

# Configurations

- name: Updating the config file to allow outside access
  copy:
    src: files/kibana.yml
    dest: /etc/kibana/kibana.yml
    follow: yes

# Starting Kibana

- name: Starting/Restarting Kibana
  service:
   name: kibana
   state: restarted
