---
# vars file for ElasticSearch
#
es_apt_key: "https://packages.elastic.co/GPG-KEY-elasticsearch"
es_repo_url: "deb https://artifacts.elastic.co/packages/7.x/apt stable main"
es_cluster_name: elasticsearch
es_node_name: node01
es_data_path: "/var/lib/elasticsearch"
es_log_path: "/var/log/elasticsearch"
es_bind_address: 0.0.0.0
es_http_port: 9200
es_discovery_seed: 0.0.0.0
es_cluster_initial: node01






