---
# Installing Elasticsearch
#

# Add Elasticsearch apt key

- name: Add Elasticsearch apt key
  apt_key:
   url: "{{ es_apt_key }}"
   state: present

# Add the Elasticsearch apt repo. of version 7

- name: Adding Elasticsearch repo
  apt_repository:
   repo: "{{ es_repo_url }}"
   state: present

# Installing Elasticsearch

- name: Install Elasticsearch
  apt:
   name: elasticsearch
   update_cache: yes
   
# Copy ElasticSearch configuration file to Elastic search serverless

- name: Coping Configuration files to Elastic Search server
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
   

 
# Start Elasticsearch
- name: Starting/Restarting Elasticsearch
  service:
   name: elasticsearch
   state: restarted
    
