---
# Installing Elasticsearch
#

# Add Elasticsearch apt key

- name: Add Elasticsearch apt key
  apt_key:
   url: "https://packages.elastic.co/GPG-KEY-elasticsearch"
   state: present

# Add the Elasticsearch apt repo. of version 7

- name: Adding Elasticsearch repo
  apt_repository:
   repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
   state: present

# Installing Elasticsearch

- name: Install Elasticsearch
  apt:
   name: elasticsearch
   update_cache: yes
   
# Copy ElasticSearch configuration file to Elastic search serverless

- name: Coping Configuration files to Elastic Search server
  copy: 
   src: files/elasticsearch.yml
   dest: /etc/elasticsearch/elasticsearch.yml
   follow: yes
   

 
# Start Elasticsearch
- name: Starting/Restarting Elasticsearch
  service:
   name: elasticsearch
   state: restarted
    
